# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "pkg-build-#{i}" do |node|
      # The most common configuration options are documented and commented below.
      # For a complete reference, please see the online documentation at
      # https://docs.vagrantup.com.

      # Every Vagrant development environment requires a box. You can search for
      # boxes at https://vagrantcloud.com/search.
      node.vm.box = "ubuntu/bionic64"

      # Disable automatic box update checking. If you disable this, then
      # boxes will only be checked for updates when the user runs
      # `vagrant box outdated`. This is not recommended.
      # node.vm.box_check_update = false

      # Create a forwarded port mapping which allows access to a specific port
      # within the machine from a port on the host machine. In the example below,
      # accessing "localhost:8080" will access port 80 on the guest machine.
      # NOTE: This will enable public access to the opened port
      # node.vm.network "forwarded_port", guest: 80, host: 8080

      # Create a forwarded port mapping which allows access to a specific port
      # within the machine from a port on the host machine and only allow access
      # via 127.0.0.1 to disable public access
      # node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

      # Create a private network, which allows host-only access to the machine
      # using a specific IP.
      #
      # pkg-build-1: 192.168.33.2
      # pkg-build-2: 192.168.33.3
      # ...
      # pkg-build-n: 192.168.33.(n + 1)
      node.vm.network "private_network", ip: "192.168.33.#{i + 1}"

      # Create a public network, which generally matched to bridged network.
      # Bridged networks make the machine appear as another physical device on
      # your network.
      # node.vm.network "public_network"

      # Share an additional folder to the guest VM. The first argument is
      # the path on the host to the actual folder. The second argument is
      # the path on the guest to mount the folder. And the optional third
      # argument is a set of non-required options.
      # node.vm.synced_folder "../data", "/vagrant_data"

      # Provider-specific configuration so you can fine-tune various
      # backing providers for Vagrant. These expose provider-specific options.
      # Example for VirtualBox:
      #
      # node.vm.provider "virtualbox" do |vb|
      #   # Display the VirtualBox GUI when booting the machine
      #   vb.gui = true
      #
      #   # Customize the amount of memory on the VM:
      #   vb.memory = "1024"
      # end
      #
      # View the documentation for the provider you are using for more
      # information on available options.

      node.vm.provider "virtualbox" do |vb|
        vb.name = "pkg-build-#{i}"
        vb.memory = "1024"
      end

      # Enable provisioning with a shell script. Additional provisioners such as
      # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
      # documentation for more information about their specific syntax and use.
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/authorized_keys"
      node.vm.provision "shell", inline: <<-SHELL
# Create the racket user
useradd -G sudo -m racket

# Let the racket user run sudo without a password
echo "racket ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/racket

# Add the host user's public key to the racket user's authorized keys
mkdir -p /home/racket/.ssh
mv /home/vagrant/authorized_keys /home/racket/.ssh/authorized_keys
chown -R racket:racket /home/racket/.ssh
SHELL
    end
  end
end
